version: '3.3'
services: 
  db:
    container_name: mysql-db
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: node
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /tmp/docker-data
    restart: always

  app:
    restart: always
    image: cunhazera/tree:latest
    environment:
      JDBC_URL: jdbc:mysql://mysql-db:3306/node?useSSL=false
      DB_USER: demo_user
      DB_PASS: demo_pass
    depends_on:
      - db
    ports:
      - 8080:8080